# Generated by Django 2.0.1 on 2018-04-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('home_types', '0003_auto_20180419_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.CharField(max_length=120)),
                ('address_to', models.CharField(max_length=120)),
                ('final_price', models.IntegerField()),
                ('floor_from', models.IntegerField(default=1)),
                ('floor_to', models.IntegerField(default=1)),
                ('observations', models.CharField(max_length=250)),
                ('packaging_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packaging_time_aprox', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=20)),
                ('service_date', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_distance_aprox', models.IntegerField(default=0)),
                ('travel_distance_aprox_label', models.CharField(default='', max_length=20)),
                ('travel_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_time_aprox', models.IntegerField(default=0)),
                ('travel_time_aprox_label', models.CharField(default='', max_length=20)),
                ('culqui_token', models.CharField(max_length=200, null=True)),
                ('error_reason', models.CharField(max_length=200, null=True)),
                ('home_type_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_home_type_from', to='home_types.HomeType')),
                ('home_type_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_home_type_to', to='home_types.HomeType')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead')),
            ],
        ),
    ]
