# Generated by Django 2.0.1 on 2018-04-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_quotations', '0002_clientquotation_truck_size_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientquotation',
            old_name='error_reason',
            new_name='culqui_charge',
        ),
    ]
