# Generated by Django 2.0.1 on 2018-06-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_quotations', '0003_auto_20180425_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
