# Generated by Django 2.0.1 on 2018-04-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometype',
            name='icon',
            field=models.CharField(choices=[('fa-home', 'Casa'), ('fa-building', 'Departamento')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hometype',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
