# Generated by Django 2.0.1 on 2018-01-29 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('districts', '0001_initial'),
        ('truck_size_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.CharField(max_length=200)),
                ('lat_long_from', models.CharField(max_length=20)),
                ('address_to', models.CharField(max_length=200)),
                ('lat_long_to', models.CharField(max_length=20)),
                ('travel_time_aprox', models.IntegerField()),
                ('district_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_from', to='districts.District')),
                ('district_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_to', to='districts.District')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead')),
                ('truck_size_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_size_types.TruckSizeType')),
            ],
        ),
    ]
