# Generated by Django 2.0.1 on 2018-01-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('trucks', '0001_initial'),
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('address_from', models.CharField(max_length=200)),
                ('address_to', models.CharField(max_length=200)),
                ('distance_price', models.IntegerField()),
                ('truck_price', models.IntegerField()),
                ('final_truck_price', models.IntegerField()),
                ('total_extra_stevedores', models.IntegerField()),
                ('extra_stevedores_price', models.IntegerField()),
                ('final_extra_stevedores_price', models.IntegerField()),
                ('base_gain', models.IntegerField()),
                ('final_gain', models.IntegerField()),
                ('district_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_from', to='districts.District')),
                ('district_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_to', to='districts.District')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.Truck')),
            ],
        ),
    ]
