# Generated by Django 2.0.1 on 2018-01-31 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_types', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='district_from',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='district_to',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='lat_long_from',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='lat_long_to',
        ),
        migrations.AddField(
            model_name='quotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='floor_from',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='floor_to',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='home_type_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_type_from', to='home_types.HomeType'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='home_type_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_type_to', to='home_types.HomeType'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lat_from',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lat_to',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lng_from',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lng_to',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='packaging_time_aprox',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='travel_distance_aprox',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='travel_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='travel_time_aprox',
            field=models.IntegerField(default=0),
        ),
    ]
