# Generated by Django 2.0.1 on 2018-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20180131_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
