# Generated by Django 2.0.1 on 2018-02-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('quotations', '0002_quotation_datetime_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='driver_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
    ]
