# Generated by Django 2.0.1 on 2018-02-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='travel_distance_aprox_label',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='travel_time_aprox_label',
            field=models.CharField(default='', max_length=20),
        ),
    ]
