<<<<<<< HEAD
# Generated by Django 2.0.1 on 2018-02-11 00:14
=======
# Generated by Django 2.0.1 on 2018-02-11 21:10
>>>>>>> cc54ab112cc909e0345f0f44ab3d21da47bf24c5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('drivers', '0001_initial'),
=======
        ('drivers', '0002_auto_20180211_2110'),
>>>>>>> cc54ab112cc909e0345f0f44ab3d21da47bf24c5
        ('quotations', '0005_quotation_driver_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
    ]
