# Generated by Django 2.0.1 on 2018-01-31 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('license_number', models.CharField(max_length=20, null=True, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('work_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.District')),
            ],
            bases=('core.person',),
        ),
    ]
