# Generated by Django 2.0.1 on 2018-01-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
