# Generated by Django 2.0.1 on 2018-02-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='driver',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
