# Generated by Django 2.0.1 on 2018-01-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20180118_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.CharField(max_length=20),
        ),
    ]
