# Generated by Django 2.0.1 on 2018-02-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20180211_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='hash_id',
            field=models.CharField(default='', max_length=8),
        ),
    ]
