# Generated by Django 2.0.1 on 2018-03-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckSizeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_stevedores', models.IntegerField(default=1)),
                ('hour_price', models.IntegerField(blank=True, null=True)),
                ('time_per_service', models.IntegerField(default=1)),
            ],
        ),
    ]
