# Generated by Django 2.0.1 on 2018-01-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quotation_price', models.IntegerField()),
                ('base_stevedor_price', models.IntegerField()),
            ],
        ),
    ]
