# Generated by Django 2.0.1 on 2018-01-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('truck_size_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('truck_size_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_size_types.TruckSizeType')),
            ],
        ),
    ]
