# Generated by Django 2.0.1 on 2018-03-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('truck_size_types', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('its_furgon', models.BooleanField(default=False)),
                ('peso_bruto', models.IntegerField(default=0, null=True)),
                ('peso_neto', models.IntegerField(default=0, null=True)),
                ('carga_util', models.IntegerField(default=0, null=True)),
                ('alto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('mts_cubicos', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_size_types.TruckSizeType')),
            ],
        ),
    ]
