# Generated by Django 2.0.1 on 2018-02-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20180211_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='carga_util',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='peso_bruto',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='peso_neto',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
