# Generated by Django 2.0.1 on 2018-01-29 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stuff', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.Quotation')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.Stuff')),
            ],
        ),
    ]
