<<<<<<< HEAD
# Generated by Django 2.0.1 on 2018-01-29 17:13
=======
# Generated by Django 2.0.1 on 2018-01-30 01:50
>>>>>>> d04651ca2f33d81e2b5be71ac0e8ba6d894b8ee1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystuff',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
