# Generated by Django 2.0.1 on 2018-02-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystuff',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
