# Generated by Django 2.0.1 on 2018-01-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_price', models.IntegerField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.Zone')),
            ],
        ),
    ]
