# Generated by Django 2.0.1 on 2018-02-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='in_price',
        ),
        migrations.RemoveField(
            model_name='district',
            name='zone',
        ),
    ]
