# Generated by Django 2.0.1 on 2018-02-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('dni', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone_number', models.CharField(default='-', max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
